topic: "世界年収アップ戦略と円安下の海外就業意思決定"
audience: "engineering managers and senior engineers"
goal: "転職/海外就職の意思決定ができる"
language: "ja"

slides:
  count: 40
  includeTableOfContents: true
  includeTitleSlide: true
  includeSummarySlide: true

marp:
  theme: "gaia"
  size: "16:9"
  paginate: true
  header: ""
  footer: ""
  style: |
    section pre code {
      font-size: 0.6em;
      line-height: 1.4;
    }

content:
  codeBlocks: false
  codeLanguage: "text"
  mermaidDiagrams: true
  bulletPointsMax: 5
  speakerNotes: true

output:
  dir: "./docs/20260214081826_global-career-strategy"
  baseName: "global-career-strategy-2026"
